services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    volumes:
      - ${DB_LOCAL_PATH}:/var/lib/mysql
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/mariadb --user=root --password=verysecret --execute=\"SHOW DATABASES;\"" ]
      interval: 2s
      timeout: 2s
      retries: 10

  application:
    image: 'application'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - '8081:8080'