spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://host.docker.internal:3306/projectDB
    username: root
    password: verysecret
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      continue-on-error: true