spring:
  datasource:
    driverClassName: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
        dialect: ${DATABASE_DIALECT}
  sql:
    init:
      continue-on-error: true